### ISSUE TITLE
Resources created under an org should rollback on any failures

### ISSUE THREAD

**Issue by hari-hypto** [hwslabs/iam#30]
During any failure in organization creation, resources (cognito user, userpool, records in the tables) are left orphaned. Clean-up resources on any failures.

**Comment by shharma-vipin** [comment]
I would like to take this up, if this is still not taken up.

**Comment by hari-hypto** [comment]
> I would like to take this up, if this is still not taken up.

Sure. Thanks for showing interest. This is an interesting problem to solve. Gist of the problem is during the org creation, we perform these steps
1. Create UserPool in AWS Cognito for the organization
2. Create an Organization in our Org table
3. Add the admin user in the user pool created in Step#1
4. Create admin policy & attach the policy to the admin user.
5. Create credential for the admin user

When any of these steps fail, we currently don't have a rollback mechanism. So the stale records in our datastore and cognito are not cleaned-up. We need to design a solution to atomically rollback if there is any failure.

Challenges:
1. There is no distributed transaction support currently available off the bat in JOOQ and Ktor. So transaction across tables should be implemented in a separate repo file.
2. Since the resources are distributed across tables and cognito, rollback should ensure that cognito resources are also deleted.

Happy to answer any further questions on this issue. Also we are available in our Slack community workspace for any discussions.

**Comment by shharma-vipin** [comment]
This issue is fixed under this PR - https://github.com/hwslabs/iam/pull/54

**Comment by karthick-vinod** [comment]
This issue has been fixed in https://github.com/hwslabs/iam/pull/56 and has been merged to main.
