### ISSUE TITLE
Send proper error response on password, phone number validation issue

### ISSUE THREAD

**Issue by hari-hypto** [hwslabs/iam#51]
Currently "Unknown server error" response is returned on password & phone number input validation. Send proper message with 4xx status code on phone number and password validation.

**Comment by ritikBhandari** [comment]
Hi,
Can I solve this issue?

**Comment by shharma-vipin** [comment]
Hey, please review this PR - https://github.com/hwslabs/iam/pull/52

**Comment by hari-hypto** [comment]
> Hi, Can I solve this issue if you don't mind?

@ritikBhandari - Absolutely, we are glad to have PRs coming from the community.

**Comment by hari-hypto** [comment]
PR #52 from @shharma-vipin fixed this issue. Resolving this ticket.

**Comment by hari-hypto** [comment]
Thanks @shharma-vipin for the contribution. Happy to collaborate and work on any other task you are interested in this repo.
